<a href="https://colab.research.google.com/github/9more/Projects/blob/main/classication_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report,roc_curve,roc_auc_score
import numpy as np
import pandas as pd

In [51]:
iris = load_iris()
X = iris.data
y = iris.target
a=[LogisticRegression(),
   SVC(),
   DecisionTreeClassifier(),
   KNeighborsClassifier()]
def data_processing(df, data, target):
  y=df.target.reshape(-1,1)
  X=df.data
  Xtrain,Xtest, ytrain, ytest= train_test_split(X, y, test_size=0.4, random_state=12)
  return Xtrain, Xtest, ytrain, ytest

def train_model(df, target):
  score =[]
  j=data_processing(df, 'data','target')
  Xtrain,Xtest, ytrain, ytest=j[0], j[1], j[2], j[3]

  for model_instance in a:
    u=model_instance.fit(Xtrain, ytrain.ravel())
    y_pred = u.predict(Xtest)
    #print(accuracy_score(ytest, y_pred))
    score.append(round(accuracy_score(ytest, y_pred),2))
    del u
    del y_pred


  best_model_index = np.argmax(np.array(score))
  print(score)
  #print(a[best_model_index])
  return a[best_model_index]

def main(df, data, target):
  j=data_processing(df, 'data','target')
  Xtrain,Xtest, ytrain, ytest=j[0], j[1], j[2], j[3]
  best_model = train_model(df, 'target')
  best_model.fit(Xtrain, ytrain.ravel())
  y_pred = best_model.predict(Xtest)
  print(confusion_matrix(ytest.ravel(), y_pred))
  print(classification_report(ytest.ravel(), y_pred))

In [52]:
main(iris, 'data','tarqet')

[0.98, 0.98, 0.95, 0.97]
[[26  0  0]
 [ 0 18  1]
 [ 0  0 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        26
           1       1.00      0.95      0.97        19
           2       0.94      1.00      0.97        15

    accuracy                           0.98        60
   macro avg       0.98      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60

