<a href="https://colab.research.google.com/github/9more/Projects/blob/main/Regression_algorithm_with_gradient_descent_optimisation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
def trainihg(X,y, grad_style='batch'):
  w=np.zero(X.shape[1])
  b= np.zero(1)
  for i in range(X.shape[0]):
    yhat=w@X.T+b
    e=np.square(yhat-y)
    if grad_style=='mini_batch':
      mini_batch
    elif grad_style=='stochastic':
      stochastic
    else:
      w1=w-0.01*e@X.T
      b1=b-0.01*e
      w,b=w1,b1
      return w,b
  def mini_batch(X,s=10):
    for _ in np.split(X,s):
      w1=w-0.01*e@X.T
      b1=b-0.01*e
      w,b=w1,b1
      return w,b
  def stochastic(X,s=10):
    for _ in np.split(X,s):
      w1=w-0.01*e@X.T
      b1=b-0.01*e
      w,b=w1,b1
      return w,b


In [ ]:
def metric(w ,b, ytest, Xtest, measure='mse'):
  if measure=='rmse':
    y=w@Xtest.T+b
    e=y-ytest
    rmse=np.sqrt(np.mean(e**2))
    return rmse
  elif measure=='mae':
    y=w@Xtest.T+b
    e=y-ytest
    mae=np.mean(np.abs(e))
    return mae
  else:
    y=w@Xtest.T+b
    e=y-ytest
    mse=np.mean(e**2)
    return mse

In [ ]:
def prediction(w,b,Xtest):
  yhat= np.dot(w,Xtest.T)+b
  return yhat

In [2]:
a= np.array([1,2,3,4,5,6,7,7,8,8,6,45,3,3,2,2,1,1])

In [7]:
x=0
for i in np.split(a,3):
  print(i)
  x+=3

[1 2 3 4 5 6]
[ 7  7  8  8  6 45]
[3 3 2 2 1 1]
